DROP TABLE IF EXISTS ODONTOLOGOS;
CREATE TABLE ODONTOLOGOS (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    APELLIDO VARCHAR(50) NOT NULL,
    NOMBRE VARCHAR(50) NOT NULL,
    NUM_MATRICULA VARCHAR(30)
);

INSERT INTO ODONTOLOGOS VALUES (DEFAULT, 'LUNA SILVA', 'EDUARDO', 'TU046715');
INSERT INTO ODONTOLOGOS VALUES (DEFAULT, 'LUIS GONZALEZ', 'JUAN CAMILO', 'TU048215');